@echo off
chcp 65001 >nul
title Wellperion Golf AI

where node >nul 2>nul
if %errorlevel% neq 0 (
    where winget >nul 2>nul
    if %errorlevel% neq 0 (
        echo Node.js 가 없고 winget 도 없습니다.
        echo https://nodejs.org 에서 LTS 설치 뒤 다시 더블클릭 해주세요.
        pause
        exit /b 1
    )
    echo Node.js 를 설치합니다. 잠시 기다려 주세요...
    winget install -e --id OpenJS.NodeJS.LTS --accept-source-agreements --accept-package-agreements
    echo Node.js 설치를 마쳤습니다.
    echo 이 창을 닫고 아이콘을 다시 한번 더블클릭 해주세요.
    pause
    exit /b 0
)

where claude >nul 2>nul
if %errorlevel% neq 0 (
    echo Claude CLI 를 설치합니다. 잠시 기다려 주세요...
    call npm install -g @anthropic-ai/claude-code
)

set "GOLF_DIR=%USERPROFILE%\Wellperion-Golf-AI"
if not exist "%GOLF_DIR%" mkdir "%GOLF_DIR%"

powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABkAGkAcgAgAD0AIAAkAGUAbgB2ADoARwBPAEwARgBfAEQASQBSAAoAJABwAGEAdABoACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJABkAGkAcgAgACcAQwBMAEEAVQBEAEUALgBtAGQAJwAKAGkAZgAgACgALQBuAG8AdAAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAkAHAAYQB0AGgAKQApACAAewAKACAAIAAkAGMAbwBuAHQAZQBuAHQAIAA9ACAAQAAnAAoACLGUsiAA8MaY06y5KMYgAOisBNUA0yAAQQBJACAAcMhQreSyLgAKAAoAIwAjACAA7cVg1QoAANOlxygAQK7c0P3FIAAE1Vy4KQBExyAA1bOUsuSyLgAKAAoAIwAjACAA0Lks0goA58ngrCAAbMK0xiAAXNVtrbTFXLggAPWyXNXksi4AIAAEyDi7qca0xXy5IADwxMDJIABKxZSy5LIuAAoACgAjACMAIABY1ZSyIAB8xwoAMQAuACAAjNbQxiAASMW0sDi7twD1rMDJIAAIzUjFIACRxzHBCgAyAC4AIACM1tDGIADIyTi7IAD1ssC8IAAIzUjFIACRxzHBIAAoAJTGCK63AAjGfcW3AOjNjMEgAPG0IABV1hXIEqxAxyAAANOlx9DFjKwgAFXWeMcpAAoAMwAuACAA/MgErCAAANMgALTGAcYgAMSsjda3ALTMbNCsuaTCuNIgAJHHMcEKADQALgAgABWstcIgADCuXbi3AIzW0MYgAPDFfbcgABXIrLkgAFzUIACRxzHBCgA1AC4AIAA0riAAAK4gAJTGfcUKAAoAIwAjACAAJMYAz6TCuNJ8tyAAKACAvVjVIADQxXTHBMi40iAAXNapxikACgB8x3THIADsxey3IAAIrJi3XLggAJiwWLJ0uiAApMKkwly4IACYsCCyHMEoAAjGOgAgAEjFtLA4uyAACM1IxSAALwAgAICsoNEgAC8AIACUxn3FKQAgAEEAZwBlAG4AdAAgAMSzbK1cuCAAgL1Y1SAA0MV0xwTIuNJ8uSAA0bwsuFy4IABEt7DG4KwsACAAsKz8rHy5IABc1SAApcc8x1y4IABp1dDMIAD0vOCsXNXksi4AIAAA06XHQMcgALCs/KzMuSAA+Lzksi4ACgAKACMAIwAgANDGWc4KAC0AIADAybTFtLDAySAASsWUsuSyLgAgAKi6dLmUsiAAlMYIrrcA3K0VyLcAdMeEuUDHIAAiAFXWeMcgAETVlMYiAFy4IABc1NzCXNXksi4ACgAtACAAjNbQxiAAHKx4xxXI9LwoAATIVNa3APzIjMEpAJSyIAAM03zH0MUgAKiwMK7AySAASsWUsuSyLgAKAC0AIAD1rN3CIABc1ATWRMcgAMDJqNDksjoAIAAiAKTC7NMgznTQ/bciACgAPNW40siypMIgAAiuwMkpACAAtwAgACIAFay1wiIAKAAIuKjCIAAIrsDJKQAgALcAIAAiAPDGmNOsuSjGIgAKAC0AIADwxpjTrLkoxiAARQBSAFAAtwDFxTS7IAApvN3CIADIyTi7QMcgAEcATQAgANiy2K4gABixNK7ksi4ACgAKACcAQAAKACAAIAAkAGUAbgBjACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBVAFQARgA4AEUAbgBjAG8AZABpAG4AZwAoACQAZgBhAGwAcwBlACkACgAgACAAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFcAcgBpAHQAZQBBAGwAbABUAGUAeAB0ACgAJABwAGEAdABoACwAIAAkAGMAbwBuAHQAZQBuAHQALAAgACQAZQBuAGMAKQAKAH0ACgA=

echo 첫 실행이면 브라우저 로그인 창이 뜹니다 — 계정은 GM 님/나우열 매니저님이 안내한 것으로 로그인 하세요.
echo 끝내려면 /exit 를 입력하세요.
echo 막히면 화면을 그대로 캡처해서 카톡으로 보내주세요.

cd /d "%GOLF_DIR%"
claude

pause
