-- 웰페리온 ERP 서버 DB 스키마 (PostgreSQL · 멱등 · 장기 결정 1·3·4 · 2026-09-03)
-- 모든 표에 tenant_id(기본 'wellperion'). 열쇠 = 회원번호 / 유형|rowKey (시트 행번호 아님).
-- 적용 = common/db.py init_schema() (migrate_sqlite_to_pg.py 가 부른다).

CREATE TABLE IF NOT EXISTS users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   TEXT NOT NULL DEFAULT 'wellperion',
  email       TEXT NOT NULL,
  name        TEXT NOT NULL,
  salt        TEXT NOT NULL,
  pw          TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'staff',
  status      TEXT NOT NULL DEFAULT 'pending',
  created_at  TEXT NOT NULL,
  approved_at TEXT,
  perms       TEXT,
  UNIQUE (tenant_id, email)
);

CREATE TABLE IF NOT EXISTS inquiries (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  id        TEXT NOT NULL,
  type      TEXT NOT NULL,
  row_key   TEXT,
  name      TEXT,
  phone     TEXT,
  status    TEXT,
  timestamp TEXT,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_inq_type_ts ON inquiries (tenant_id, type, timestamp);

CREATE TABLE IF NOT EXISTS members (
  tenant_id   TEXT NOT NULL DEFAULT 'wellperion',
  member_no   TEXT NOT NULL,
  scope       TEXT NOT NULL,
  name        TEXT,
  phone       TEXT,
  kind        TEXT,
  kind2       TEXT,
  program     TEXT,
  reg_class   TEXT,
  reg_seq     TEXT,
  reg_date    TEXT,
  start_date  TEXT,
  end_date    TEXT,
  loss_date   TEXT,
  remain_days TEXT,
  owner       TEXT,
  data        TEXT NOT NULL,
  synced_at   TEXT NOT NULL,
  PRIMARY KEY (tenant_id, member_no, scope)
);
CREATE INDEX IF NOT EXISTS ix_mem_scope_end ON members (tenant_id, scope, end_date);
CREATE INDEX IF NOT EXISTS ix_mem_phone ON members (tenant_id, phone);
CREATE INDEX IF NOT EXISTS ix_mem_name ON members (tenant_id, name);

CREATE TABLE IF NOT EXISTS sync_meta (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  k         TEXT NOT NULL,
  v         TEXT,
  PRIMARY KEY (tenant_id, k)
);

-- 업무·결재 SSOT 미러 (sync_todo.py · 배 922 레인 T). 열쇠 = 항목 id(TODO-…) — 행번호가 아니다.
CREATE TABLE IF NOT EXISTS todo_items (
  tenant_id   TEXT NOT NULL DEFAULT 'wellperion',
  id          TEXT NOT NULL,
  title       TEXT,
  category    TEXT,
  dept        TEXT,
  owner       TEXT,
  status      TEXT,
  creator     TEXT,
  created     TEXT,
  modified    TEXT,
  start_date  TEXT,
  end_date    TEXT,
  done_date   TEXT,
  data        TEXT NOT NULL,
  synced_at   TEXT NOT NULL,
  PRIMARY KEY (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_todo_status ON todo_items (tenant_id, status);
CREATE INDEX IF NOT EXISTS ix_todo_created ON todo_items (tenant_id, created);

CREATE TABLE IF NOT EXISTS approvals (
  tenant_id     TEXT NOT NULL DEFAULT 'wellperion',
  id            TEXT NOT NULL,
  title         TEXT,
  owner         TEXT,
  approvers     TEXT,
  appr_status   TEXT,
  sign_head     TEXT,
  sign_gm       TEXT,
  sign_ceo      TEXT,
  completed_at  TEXT,
  created       TEXT,
  data          TEXT NOT NULL,
  synced_at     TEXT NOT NULL,
  PRIMARY KEY (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_appr_status ON approvals (tenant_id, appr_status);

-- 점검 미러 (배 922 레인 S · 2026-09-03) — sync_check.py 가 점검 GAS 응답을 부서·종류·열쇠로 그대로 싣는다.
-- kind = board(시설 날짜) · ledger(날짜|성별) · today_live(날짜) · monthly(월) · weekly('-'). 화면은 GAS 응답 모양 그대로 읽는다.
CREATE TABLE IF NOT EXISTS check_records (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  dept      TEXT NOT NULL,
  kind      TEXT NOT NULL,
  key       TEXT NOT NULL,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, dept, kind, key)
);

-- 종합접수처 미러 (sync_reception.py · 배 922 · 2026-09-03). 열쇠 = 접수ID / 습득ID / 휴회접수 행번호(intakeRow).
-- 점수판(all·week·month)·담당자 목록은 GAS 응답 그대로 sync_meta reception_scoreboard_* / reception_staff_names 에 둔다.
CREATE TABLE IF NOT EXISTS reception_items (
  tenant_id  TEXT NOT NULL DEFAULT 'wellperion',
  reg_id     TEXT NOT NULL,
  category   TEXT,
  dept       TEXT,
  status     TEXT,
  created_at TEXT,
  data       TEXT NOT NULL,
  synced_at  TEXT NOT NULL,
  PRIMARY KEY (tenant_id, reg_id)
);
CREATE TABLE IF NOT EXISTS lost_found (
  tenant_id  TEXT NOT NULL DEFAULT 'wellperion',
  found_id   TEXT NOT NULL,
  status     TEXT,
  created_at TEXT,
  data       TEXT NOT NULL,
  synced_at  TEXT NOT NULL,
  PRIMARY KEY (tenant_id, found_id)
);
CREATE TABLE IF NOT EXISTS hold_items (
  tenant_id  TEXT NOT NULL DEFAULT 'wellperion',
  intake_row TEXT NOT NULL,
  status     TEXT,
  done       BOOLEAN NOT NULL DEFAULT FALSE,   -- 접수 GAS hold_done_keys(처리메모 '휴회완료') 조인 결과
  applied_at TEXT,
  data       TEXT NOT NULL,
  synced_at  TEXT NOT NULL,
  PRIMARY KEY (tenant_id, intake_row)
);

-- 쓰기 관문 원장 (api_write.py · 배 961 · 2026-09-03). 화면이 시트에 쓰는 모든 payload 가 GAS 로 가기 전에 여기 먼저 남는다.
-- gas_status = pending(전달 전) · ok · gas-error(GAS 가 ok:false) · forward-failed(GAS 에 못 닿음 → 화면이 GAS 직접 폴백).
CREATE TABLE IF NOT EXISTS write_log (
  id           BIGSERIAL PRIMARY KEY,
  tenant_id    TEXT NOT NULL DEFAULT 'wellperion',
  at           TEXT NOT NULL,
  action       TEXT NOT NULL,
  payload      JSONB NOT NULL,
  user_email   TEXT,
  gas_status   TEXT NOT NULL,
  gas_response JSONB
);
CREATE INDEX IF NOT EXISTS ix_write_log_action ON write_log (tenant_id, action, at);
-- 중복 쓰기 가림 (api_write._idem_hit · 배 960 M7 · 2026-09-04). 응답만 유실돼 같은 요청이 다시 와도 GAS 를 두 번 치지 않게
-- 화면이 실어 보낸 요청 열쇠(payload.idem)로 최근 10분을 찾는다. 열쇠가 없는 행은 인덱스에 담지 않는다(대부분의 옛 행).
CREATE INDEX IF NOT EXISTS write_log_idem_idx ON write_log (tenant_id, (payload->>'idem'), at) WHERE payload ? 'idem';

-- 공개 접수 폼 이중기록 (api_intake.py · 배 960 · 2026-09-03). 폼 본문을 GAS 보다 먼저 적는다 — GAS 가 죽어도 여기 남는다.
-- gas_status = pending · HTTP 코드('200' 정상) · skipped(selftest) · error:<사유>. form=selftest 는 tenant 'selftest'.
CREATE TABLE IF NOT EXISTS intake_log (
  id           BIGSERIAL PRIMARY KEY,
  tenant_id    TEXT NOT NULL DEFAULT 'wellperion',
  form         TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  payload      JSONB NOT NULL,
  gas_status   TEXT NOT NULL DEFAULT 'pending',
  gas_response TEXT
);
CREATE INDEX IF NOT EXISTS intake_log_tenant_form_idx ON intake_log (tenant_id, form, received_at);

-- 서버 원본 되밀기 칸 (origin_switch·pushback.py · 배 960 레인 J · 2026-09-04). 두 원장에 같은 세 칸을 덧붙인다.
--   server 모드 행은 gas_status='queued' 로 남고 raw_body(받은 본문 그대로)를 이고 있다가, pushback.py 가 GAS 로 되민 뒤
--   pushed_at 을 적고 raw_body 를 지운다(사진·서명 base64 를 계속 들고 있지 않게). push_tries = 되밀기 시도 횟수(5회 상한).
--   dual 모드 행은 세 칸이 비어 있다 — 종전 동작 그대로.
ALTER TABLE intake_log ADD COLUMN IF NOT EXISTS pushed_at  TEXT;
ALTER TABLE intake_log ADD COLUMN IF NOT EXISTS push_tries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE intake_log ADD COLUMN IF NOT EXISTS raw_body   TEXT;
ALTER TABLE write_log  ADD COLUMN IF NOT EXISTS pushed_at  TEXT;
ALTER TABLE write_log  ADD COLUMN IF NOT EXISTS push_tries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE write_log  ADD COLUMN IF NOT EXISTS raw_body   TEXT;
-- 1분 cron 이 매번 원장 전체를 훑지 않게 — 되밀 행만 담는 부분 인덱스(대개 0행).
CREATE INDEX IF NOT EXISTS intake_log_queued_idx ON intake_log (id) WHERE gas_status = 'queued' AND pushed_at IS NULL;
CREATE INDEX IF NOT EXISTS write_log_queued_idx  ON write_log  (id) WHERE gas_status = 'queued' AND pushed_at IS NULL;

-- 강습 회원관리 미러 (sync_lesson.py · 배 922 레인 W · 2026-09-03). GAS 읽기 응답을 통째로 싣는다.
-- kind = stats(key=type|scope) · roster(type) · registry(type · 전 구간, 날짜는 API 가 등록일로 자른다).
CREATE TABLE IF NOT EXISTS lesson_records (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  kind      TEXT NOT NULL,
  key       TEXT NOT NULL,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, kind, key)
);

-- 카톡전송관리 방 목록 미러 (sync_kakao.py · 배 922 레인 W · 2026-09-03). 열쇠 = 방 이름 · ord = 시트 순.
CREATE TABLE IF NOT EXISTS kakao_rooms (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  name      TEXT NOT NULL,
  prefix    TEXT,
  ord       INTEGER NOT NULL DEFAULT 0,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, name)
);

-- 시모 퍼널 집계 거울 (sync_funnel.py · api_funnel.py · 배 960 · 2026-09-03). 열쇠 = 액션 + 정렬한 쿼리(from=&to=). 응답 통째.
CREATE TABLE IF NOT EXISTS funnel_cache (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  action    TEXT NOT NULL,
  params    TEXT NOT NULL DEFAULT '',
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, action, params)
);

-- 브로제이(외부 CRM) 매출·입장 적재 (sync_brojay.py · api_brojay.py · 배 959 · 2026-09-04).
-- kind = sales(일 매출·계약 건별) · entries(입장) · key = 날짜 YYYY-MM-DD. 응답 JSON 을 통째로 싣는다 —
-- 브로제이가 주는 칸 이름을 우리가 정규화하면 그쪽이 바뀔 때마다 깨진다(lesson_records 와 같은 이유).
CREATE TABLE IF NOT EXISTS brojay_records (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  kind      TEXT NOT NULL,
  key       TEXT NOT NULL,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, kind, key)
);

-- 공용 보드(GAS action=board) 미러 (sync_board.py · api_board.py · 배 926 · 2026-09-04).
-- GM_TASK_OWNERS 등 화면 여러 곳이 쓰는 범용 키-값 저장소를 키별로 통째 미러 — GAS 응답 지연(3.7~24초)이
-- 화면 타임아웃(8초)에 걸려 담당 칸이 빈 화면이 되던 문제를 없앤다. 목록 = sync_board.py BOARD_KEYS.
CREATE TABLE IF NOT EXISTS board_cache (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  key       TEXT NOT NULL,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, key)
);

-- 매출·지출 집계 거울 (sync_sales.py · api_sales.py · 배 960 레인 E · 2026-09-04).
-- gas = salesops(매출 배관 .deploy-salesops) · proc(운영요약) · deptrep(보고시트) · action = GAS 액션 ·
-- params = 정렬한 나머지 쿼리(month=8 · range=A1:S20&sheet=4 · 빈값). 응답을 통째로 싣는다 — 화면이 GAS 모양 그대로 받는다.
-- 무거운 집계(sales_dept_pub 실측 31초)를 화면이 매번 기다리던 것을 없앤다. 목록·TTL = sync_sales.py jobs().
CREATE TABLE IF NOT EXISTS sales_cache (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  gas       TEXT NOT NULL,
  action    TEXT NOT NULL,
  params    TEXT NOT NULL DEFAULT '',
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, gas, action, params)
);

-- 소형 GAS 읽기 거울 (sync_misc.py · api_misc.py · 배 960 #9 · 2026-09-04).
-- sales_cache 와 같은 모양(gas, action, params) — 배 960 §2 #9 표(지출현황·리셉션 업무·라커관리·renewal 개인 GAS)
-- 중 실제 쓰임 근거(page_ping.json last_open)가 있고 읽기 전용인 것만 담는다. 목록 = sync_misc.py GAS_ENV.
CREATE TABLE IF NOT EXISTS misc_cache (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  gas       TEXT NOT NULL,
  action    TEXT NOT NULL,
  params    TEXT NOT NULL DEFAULT '',
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, gas, action, params)
);

-- 문의 유입 경로 칸 (배 925 · status/briefs/CMO-유입경로-발행원장-정의서-20260903.md 표 A · 2026-09-05).
-- channel_code 11종(6종 채널+5종 특수값, unknown=기록없음) + post_id(publish_ledger 참조, 없으면 NULL).
-- 기존 문의 행은 DEFAULT 'unknown'이 그대로 채운다(GM 확정: 소급 안 채움 = unknown 명시값으로 채움).
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS channel_code        TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS post_id             TEXT;
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS channel_captured_at TEXT;
CREATE INDEX IF NOT EXISTS ix_inq_channel ON inquiries (tenant_id, channel_code, post_id);

-- 콘텐츠 발행 원장 (배 925 · 같은 정의서 표 B · 2026-09-05). review_queue.json 179건의 이관처.
-- 핵심 칸만 컬럼으로 두고, 제작·검수 파이프라인 부속 칸(folder/preview/slides/... )은 meta JSONB 한 칸에 그대로 싣는다
-- (버리지 않음 — 정의서 §3). reach/save/inquiry_count 는 저장하지 않는다(매번 계산, 약속 L01).
CREATE TABLE IF NOT EXISTS publish_ledger (
  tenant_id     TEXT NOT NULL DEFAULT 'wellperion',
  post_id       TEXT NOT NULL,
  title         TEXT,
  channel_code  TEXT NOT NULL DEFAULT 'unknown',
  format        TEXT NOT NULL DEFAULT 'unknown',
  external_url  TEXT,
  status        TEXT,
  published_at  TEXT,
  note          TEXT,
  meta          JSONB,
  synced_at     TEXT NOT NULL,
  PRIMARY KEY (tenant_id, post_id)
);
