-- 웰페리온 ERP 서버 DB 스키마 (PostgreSQL · 멱등 · 장기 결정 1·3·4 · 2026-09-03)
-- 모든 표에 tenant_id(기본 'wellperion'). 열쇠 = 회원번호 / 유형|rowKey (시트 행번호 아님).
-- 적용 = common/db.py init_schema() (migrate_sqlite_to_pg.py 가 부른다).

CREATE TABLE IF NOT EXISTS users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   TEXT NOT NULL DEFAULT 'wellperion',
  email       TEXT NOT NULL,
  name        TEXT NOT NULL,
  salt        TEXT NOT NULL,
  pw          TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'staff',
  status      TEXT NOT NULL DEFAULT 'pending',
  created_at  TEXT NOT NULL,
  approved_at TEXT,
  perms       TEXT,
  UNIQUE (tenant_id, email)
);

CREATE TABLE IF NOT EXISTS inquiries (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  id        TEXT NOT NULL,
  type      TEXT NOT NULL,
  row_key   TEXT,
  name      TEXT,
  phone     TEXT,
  status    TEXT,
  timestamp TEXT,
  data      TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_inq_type_ts ON inquiries (tenant_id, type, timestamp);

CREATE TABLE IF NOT EXISTS members (
  tenant_id   TEXT NOT NULL DEFAULT 'wellperion',
  member_no   TEXT NOT NULL,
  scope       TEXT NOT NULL,
  name        TEXT,
  phone       TEXT,
  kind        TEXT,
  kind2       TEXT,
  program     TEXT,
  reg_class   TEXT,
  reg_seq     TEXT,
  reg_date    TEXT,
  start_date  TEXT,
  end_date    TEXT,
  loss_date   TEXT,
  remain_days TEXT,
  owner       TEXT,
  data        TEXT NOT NULL,
  synced_at   TEXT NOT NULL,
  PRIMARY KEY (tenant_id, member_no, scope)
);
CREATE INDEX IF NOT EXISTS ix_mem_scope_end ON members (tenant_id, scope, end_date);
CREATE INDEX IF NOT EXISTS ix_mem_phone ON members (tenant_id, phone);
CREATE INDEX IF NOT EXISTS ix_mem_name ON members (tenant_id, name);

CREATE TABLE IF NOT EXISTS sync_meta (
  tenant_id TEXT NOT NULL DEFAULT 'wellperion',
  k         TEXT NOT NULL,
  v         TEXT,
  PRIMARY KEY (tenant_id, k)
);
